class APiMange {
  // static const String baseurl = "http://127.0.0.1:8000/api";
  // static const String baseurlImage = "http://127.0.0.1:8000";
  static const String baseurl = "https://blossomblue.realestate/public/api";
  static const String baseurlImage = "https://blossomblue.realestate/public";
  static const String newproperty = "$baseurl/newproperty";
  static const String recommendhotel = "$baseurl/recommendhotel";
  static const String mostview = "$baseurl/mostview";
  static const String forcountry = "$baseurl/forcountry";
  static const String search = "$baseurl/searchnameorcountrey?search";
  static const String filterdata = "$baseurl/filterdata";
  static const String catogerydata = "$baseurl/catogerydata";
  static const String propertydetalis = "$baseurl/propertydetalis";
  static const String addreport = "$baseurl/addreport";
  static const String addquery = "$baseurl/addenqueris";
  static const String addproperty = "$baseurl/addproperty";
  static const String updateviews = "$baseurl/updateviews";
  //--------------------------------------------------------------------------------------------------------------------------
  // static const String login = "$baseurl/auth/login";
  static const String register = "$baseurl/register";
  static const String login = "$baseurl/login";
  static const String resetPass = "$baseurl/reset-password";
  static const String forgotPassword = "$baseurl/forgot-password";
  static const String logout = "$baseurl/logout";
  static const String verfyemail = "$baseurl/verify-email";
  static const String changePassword = "$baseurl/changePassword";
  static const String userData = "$baseurl/user";
  static const String changeuserData = "$baseurl/updateUserInfo";
  // static const String propertydetalis = "$baseurl/propertydetalis";
  // static const String getfavorute = "$baseurl/wishlists"; //id
  // static const String mostview = "$baseurl/mostview"; //id
  // static const String gteCartList = "$baseurl/carts"; //id
  // static const String gteAddCartList = "$baseurl/carts/add"; //id
  // static const String gteAddressuser = "$baseurl/user/shipping/address"; //id
  // static const String getaddress = "$baseurl/user/shipping/address";
  // static const String requestShope = "$baseurl/send-seller-request";
  // static const String sendcontact = "$baseurl/send-contact";
  // static const String products = "$baseurl/products/category";
  ///7?page=1
  // static const String forgotPasswordRoute = "/forgotPassword";
  // static const String resetPasswordRoute = "/resetPassword";
}
